source:
  type: local
  path: ./example
  recursive: true
  include:
    - '*.jpg'
    - '*.jpeg'
    - '*.png'
    - '*.gif'
    - '*.webp'
    - '*.mp4'
    - '*.webm'
    - '*.mp3'
    - '*.wav'
    - '*.pdf'
    - '*.txt'
    - '*.md'
  exclude:
    - '.DS_Store'
    - 'thumbs/'

buckets:
  - label: Cats
    path: ./example/sorted/cats
    shortcut: '1'
  - label: Dogs
    path: ./example/sorted/dogs
    shortcut: '2'
  - label: Some Other Third Thing
    path: ./example/sorted/review
    shortcut: '3'
